### ISSUE TITLE
Newline as separator not working?

### ISSUE THREAD

**Issue by jeremybawcom** [PeterTheobald/GSheet-MultiSelect#1]
the script notes that newline would be supported:
> // Newline in quotes is a valid separator to have each item on its own line.

I've tried single and double quotes
Sep="Newline"
Sep='Newline'

And it's just returning those Newline strings as the separator. Am I doing this wrong?

**Comment by PeterTheobald** [comment]
Yes you are typing the word "Newline" instead of entering an actual newline.
"this has
a newline"

**Comment by jeremybawcom** [comment]
*facepalm* got it. resolved, thank you so much for the quick reply 🙏🙏🙏

**Comment by jeremybawcom** [comment]
closing
